### ISSUE TITLE
Should settings.xml go into AppData folder instead?

### ISSUE THREAD

**Issue by nmeier** [sirWest/AudioSwitch#12]
I realize now why the installer asks to install AudioSwitch into the user's app data folder - stubborn as I am I installed it into Program Files with admin rights - going into Settings and having AudioSwitch try to save those fails as Settings doesn't write settings.xml into an app data folder - if I had my C env up I'd look into patching that.

Thanks

**Comment by jwigley** [comment]
I also ran into the same issue. I installed into Program Files, but then AudioSwitch now crashes every time it tries to save settings.xml.

```
************** Exception Text **************
System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\AudioSwitch\Settings.xml' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path)
   at AudioSwitch.Classes.Settings.Save()
   at AudioSwitch.Forms.FormSwitcher.FormSwitcher_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at AudioSwitch.Forms.FormSwitcher.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by namelessrabbit** [comment]
Yep, same here. Everything fine while using admin privileges. 

Since my instance crashes on every termination it always keeps my system from shutting down. Hence I'd vote for removing the option to install it to Program Files unless it can be fixed another way.

**Comment by FaffeF** [comment]
Same issue, same error message.

**Comment by sirWest** [comment]
new logic for setup & settings file in latest version: now settings & error log will always go to AppData folder regardless of installation folder, which now is Program Files by default but can also be changed.
