### ISSUE TITLE
Crashes if working directory is not where the exe is

### ISSUE THREAD

**Issue by ascott18** [sirWest/AudioSwitch#13]
The following error occurs when the program is run when the working directory is not the install location of the program. 

```
System.IO.FileNotFoundException was unhandled
Message: An unhandled exception of type 'System.IO.FileNotFoundException' occurred in mscorlib.dll
Additional information: Could not find file 'C:\Windows\system32\Settings.xml'.
```

Furthermore, the error log file is not where the dialog from the program reports it to be - it ends up where ever the working directory is - in this case, I found it in C:\Windows\SysWOW64. I had to get the above error by opening Visual Studio for debugging since I couldn't figure out where the error file might be, or if it was even being created. Here's the full stack trace from the log file:

```
System.IO.FileNotFoundException: Could not find file 'C:\Windows\system32\Settings.xml'.
File name: 'C:\Windows\system32\Settings.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at AudioSwitch.Classes.Settings.Load()
   at AudioSwitch.Classes.Program.Main(String[] args)
```

Here's an article about how to properly get the directory that contains the exe: https://msdn.microsoft.com/en-us/library/aa457089.aspx

**Comment by ascott18** [comment]
Fixed with https://github.com/sirWest/AudioSwitch/pull/14

**Comment by sirWest** [comment]
Thanks @ascott18 for finding the problem, it's fixed now :)
