### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by PaladinBrewer** [sirWest/AudioSwitch#160]
I've tried reinstalling but it did not help

Log Entry: 6/9/2019 9:44:00 AM

System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: Unrecognized configuration section runtime. (C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.config line 13)
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(String configKey)
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Xml.Serialization.TempAssembly.get_UseLegacySerializerGeneration()
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at AudioSwitch.Classes.Settings.Save()
   at AudioSwitch.Classes.Settings.Load()
   at AudioSwitch.Classes.Program.Main(String[] args)
-------------------------------

**Comment by r4zmuz** [comment]
This error message indicates that one of the .NET Framework's configuration files is corrupt. The most common fix for this is to visit WindowsUpdate and install all available .NET Framework updates. If that doesn't work, try re-installing the .NET Framework. https://dotnet.microsoft.com/download/dotnet-framework

**Comment by karcsika061** [comment]
I have the same problem but I have the latest .NET on my computer.

**Comment by jjw410** [comment]
I'm getting this as well, the program's also been automatically switching devices rapidly, and in general not working well the last 2 days. Currently pretty unusable.
