### ISSUE TITLE
My ErrorLog (when launching AudioSwitch)

### ISSUE THREAD

**Issue by HonZuna** [sirWest/AudioSwitch#28]
Log Entry: 04.09.2015 17:43:23

System.ArgumentOutOfRangeException: InvalidArgument=Hodnota 0 není platnou hodnotou pro argument index.
Název parametru: index
   v System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   v AudioSwitch.Forms.FormSwitcher.<SetTrayIcons>b__14(CDevice x)
   v System.Collections.Generic.List`1.Find(Predicate`1 match)
   v AudioSwitch.Forms.FormSwitcher.SetTrayIcons()
   v AudioSwitch.Forms.FormSwitcher..ctor()

**Comment by bolaum** [comment]
I'm getting the same error, but in english:

```
Log Entry: 9/17/2015 5:31:37 PM

System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ListView.SelectedListViewItemCollection.get_Item(Int32 index)
   at AudioSwitch.Forms.FormSwitcher.<SetTrayIcons>b__14(CDevice x)
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at AudioSwitch.Forms.FormSwitcher.SetTrayIcons()
   at AudioSwitch.Forms.FormSwitcher..ctor()
   at AudioSwitch.Classes.Program.Main(String[] args)
```

**Comment by bolaum** [comment]
Uninstalling the old one and Installing version 2.1.1.0 fixed it for me!
