### ISSUE TITLE
Error conflicting with DFX Audio Enhancer

### ISSUE THREAD

**Issue by SP77** [sirWest/AudioSwitch#42]
Hello, sirWest. Thanks for an awesome and indispensable program. It is one of the first installed on a new system. I've been using it without problems for a few months now but, after installing DFX Audio Enhancer yesterday I received this error message:

Log Entry: 12/1/2015 4:42:36 AM

System.IO.FileNotFoundException: Could not find file 'c:\windows\system32\dfx11.ico'.
File name: 'c:\windows\system32\dfx11.ico'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at AudioSwitch.Classes.DeviceIcons.GetIcon(String iconPath)
   at AudioSwitch.Classes.DeviceIcons.Add(String iconPath)
   at AudioSwitch.Forms.FormSwitcher.RefreshDevices(EDataFlow renderType)
   at AudioSwitch.Forms.FormSwitcher..ctor()
   at AudioSwitch.Classes.Program.Main(String[] args)

The .ico file listed is present and in the correct directory. Both were set to auto start. Figuring that was causing the issue somehow, I ran AS after the crash and it popped up again. I also updated to the latest version 2.1.2.0. Still no luck. Any assistance in helping me figure this out would be appreciated. Thanks in advance and congrats on a great program. I can't believe Microsoft hasn't implemented it into the OS yet.

Santos

**Comment by sirWest** [comment]
fixed in 2.1.3
