### ISSUE TITLE
UI doesn't work in Win10 Pro

### ISSUE THREAD

**Issue by odyodyodys** [sirWest/AudioSwitch#43]
AudioSwitch starts and the icon is shown in the taskbar, however:
- Left clicking the taskbar icon does nothing,
- Right clicking the taskbar icon displays the context menu. Clicking on **Settings** displays the following unhandled exception:

```
See the end of this message for details on invoking just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Win32 handle that was passed to Icon is not valid or is the wrong type.
   at System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   at System.Drawing.Icon..ctor(IntPtr handle)
   at System.Drawing.Icon.FromHandle(IntPtr handle)
   at AudioSwitch.Classes.DeviceIcons.GetIcon(String iconPath)
   at AudioSwitch.Classes.EndPoints.GetAllDeviceList()
   at AudioSwitch.Forms.FormSettings.FormSettings_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AudioSwitch
    Assembly Version: 2.1.3.0
    Win32 Version: 2.1.3
    CodeBase: file:///C:/Program%20Files%20(x86)/AudioSwitch/AudioSwitch.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:
<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

In the unhandled exception if I click continue the **Settings** dialog is shown but clicking close on it also throws an unhandled exception:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AudioSwitch.Forms.FormSettings.FormSettings_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.127.1 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AudioSwitch
    Assembly Version: 2.1.3.0
    Win32 Version: 2.1.3
    CodeBase: file:///C:/Program%20Files%20(x86)/AudioSwitch/AudioSwitch.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.93.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.79.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:
<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by ghost** [comment]
Confirmed for 2.3.1.0 on Win 10 Pro, it won't show UI on a left click on the tray icon. However I don't see any error message, even if running the binary from a terminal. Deleting configuration file didn't help.

AudioSwitch works properly with hotkeys to switch device.
Changing action on right-click to "menu [...] otherwise [...]" will prevent further access to settings unless configuration is edited.

**Comment by n1c0l4** [comment]
Same issue, Win 10 Home.
[ErrorLog.txt](https://github.com/sirWest/AudioSwitch/files/72412/ErrorLog.txt)

**Comment by icaptnbob** [comment]
2.1.3 doesn't work properly for me. Left-click doesn't show UI, right-click shows menu, including devices and settings. Settings button works from this settings option. Double-click also doesn't show the settings as it did in 2.0 used on another PC.
Using Windows 10 Pro on a MS Surface 3 Pro. I've tested with the Pen and the touch-pad cursor as the two behave differently in some apps.

**Comment by sirWest** [comment]
Are you using a higher/non-standard DPI settings? AudioSwitch has currently
no support for non-default DPI scaling and thus might behave unexpectedly
on such a screen. This is also 99% reason for me to rewrite it as 3.0 using
WPF/xaml GUI.

**Comment by ghost** [comment]
Scaling was the issue indeed, here is how to disable it for AudioSwitch alone.
You'll need to log out and in again.

<img width="429" alt="disablescaling" src="https://cloud.githubusercontent.com/assets/54298/12010224/91782c92-ac9e-11e5-93d7-789ca30c88d8.PNG">

**Comment by n1c0l4** [comment]
The fix don't work for me. Here the log after the DPI scaling setted.

"Log Entry: 27/12/2015 14:10:49

System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.
   in AudioSwitch.Forms.FormSettings.FormSettings_FormClosing(Object sender, FormClosingEventArgs e)
   in System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   in System.Windows.Forms.Form.RaiseFormClosingOnAppExit()
   in System.Windows.Forms.Application.ExitInternal()
   in System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   in System.Windows.Forms.Control.WndProcException(Exception e)
   in System.Windows.Forms.Control.ControlNativeWindow.OnThreadException(Exception e)
   in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)"

**Comment by odyodyodys** [comment]
Didn't work for me either, although after the second left click at the
taskbar button the context menu appeared, which didn't without disabling
scaling.
I do also have altered dpi (150%) due to high dpi screen.
Note to the dev: I don't think you have to move to wpf to be able to
support high dpi. It's some how sorted out by default and you can also
alter the behavior/ui on high or low dpis.

**Comment by Winand** [comment]
scaling fix works on win10x64. though preferences layout is broken then.
Tray icon also looks... not good. Maybe standard windows sound icon can be used (as an option)?
![image](https://cloud.githubusercontent.com/assets/53390/12016193/330af6ce-ad59-11e5-991c-eabb90566508.png)

I set device switching on right button in preferences. As i understand in this case one should open UI then right-click on tray icon to open menu, but sometimes this action switches devices anyway.

**Comment by icaptnbob** [comment]
Great, that works for me. Scaling is set at 150%, resolution is 2160x1440.
Thanks a lot

**Comment by medoix** [comment]
Works for me also (disabling the scaling option) but now the settings menu is all over the place but still semi usable.

**Comment by tkoft** [comment]
Disabling scaling worked for me.  Preferences layout also smushed into crap, though.  But the application's usable now at least.  Thanks!

**Comment by PiTRiS87** [comment]
same issue as #45 
Thanks for the hotfix, this works

**Comment by sirWest** [comment]
Try the latest version, should have it fixed
