### ISSUE TITLE
W10 Crash on Launch

### ISSUE THREAD

**Issue by dnalloheoj** [sirWest/AudioSwitch#6]
Log Entry: 6/2/2015 10:49:10 AM

System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderSettings.Read12_Settings()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at AudioSwitch.Classes.Settings.Load()
   at AudioSwitch.Classes.Program.Main(String[] args)

---

This is using Windows 10 build 10130 and Audioswitch v2.0 RC7. Completely understand if this isn't being actively developed for W10 at the moment, just figured I'd pass it along as the error message told me to!

Also had to 'Run as Administrator' to get it to install. Otherwise I got a plethora of 'Access is Denied' errors. 

Thanks!

Edit: Settings.xml is blank as per the question asked here: https://code.google.com/p/audioswitch/issues/detail?id=60

Edit2: Deleting Settings.xml and re-installing solves the issue and it launches fine, as per instructions here: https://code.google.com/p/audioswitch/issues/detail?id=61

**Comment by sirWest** [comment]
delete the empty Settings.xml file and reinstall AudioSwitch. Running as administrator should not be required in normal circumstances, there must be some custom security options on the folders where you are trying to install. By default it installs into users' local app folder with necessary access as regular user.
