### ISSUE TITLE
Microsoft .NET Framework  - Element not found

### ISSUE THREAD

**Issue by alchemyforbeginners** [sirWest/AudioSwitch#85]
This program was working flawlessly yesterday. I did remount my heatsink, and pulled the RAM out of the slots at the same time. As well as the GPU. Could this have anything to do with the problem?

```
Log Entry: 15/07/2016 10:50:52 AM

System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at AudioSwitch.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(EDataFlow dataFlow, ERole role)
   at AudioSwitch.Controls.VolumeBar.RegisterDevice(EDataFlow RenderType)
   at AudioSwitch.Forms.FormSwitcher..ctor()
   at AudioSwitch.Classes.Program.Main(String[] args)
-------------------------------
```

**Comment by alchemyforbeginners** [comment]
OK, I'm pretty sure I worked out the problem. I didn't have any audio devices connected, after I'd been playing around inside it. Once I connected the speakers, it worked again. Headphones too. So, not a big issue. Still, a fix might be welcome. Kind regards, and keep up the great work!
