### ISSUE TITLE
Windows 10 Anniversary Update crashes AudioSwitch

### ISSUE THREAD

**Issue by pillarsforvr** [sirWest/AudioSwitch#95]
AudioSwitch crashes after updating to the recent Windows 10 Anniversary Update.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at AudioSwitch.Classes.WindowPosition.GetTaskbarPosition(Rectangle& bounds)
   at AudioSwitch.Classes.WindowPosition.GetWindowPosition(NotifyIcon notifyicon, Int32 windowwidth, Int32 windowheight)
   at AudioSwitch.Forms.FormSwitcher.SetSizes()
   at AudioSwitch.Forms.FormSwitcher.DeviceRemoved(String devID)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

AudioSwitch
    Assembly Version: 2.1.3.0
    Win32 Version: 2.1.3
##     CodeBase: file:///C:/Program%20Files%20(x86)/AudioSwitch/AudioSwitch.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1586.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by sly67** [comment]
Mine crashed too but after removing `settings.xml` from `AppData\Local\AudioSwitch` the software worked again.

**Comment by pillarsforvr** [comment]
I'll try that once the Anniversary Update is more stable. I've rolled back
the update so I can't test right now.

**Comment by ghost** [comment]
Mine was working perfectly fine on the anniversary update. But after i installed a Bluetooth Dongle Driver and used it for audio it keeps crashing even after multiple reinstall.

**Comment by ghost** [comment]
Removing settings.xml worked too for me.

**Comment by xuvvy** [comment]
# TO FIX THIS:

Go to the the _.../AppData/Local/_ folder, right click the **Settings.xml file** and go **_Properties_**.
**Uncheck the _Hidden_ box and click _Apply_.**
